import Head from 'next/head'
import { Box, Button, Container, Input } from '@chakra-ui/react'
import React, { useState } from "react";
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  const [date, setDate] = useState('');
  return (
    <>
      <Head>
        <title>Examen Next - Médéric CAREIL</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Box>
          <h1>Quand puis-déployer ?</h1>

          <Input type="date" onChange={(date: any) => {
            setDate(date.target.value);
          }} mt={5} />

          <Button
            onClick={(e) => {
              e.preventDefault();
              router.push('/icandeploy/' + date);
            }}
            mt={5}
          >
            Rechercher            
          </Button>
      
        </Box>
      </Container>
    </>
  )
}
